server:
    port: 8189
    servlet:
        context-path: /app
utils:
  cart:
    prefix: SPRING_WEB_
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: berbedos31
      driver-class-name: org.postgresql.Driver
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
    flyway:
      baseline-on-migrate: true
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.web: ERROR
    com.korsuk: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level%logger{36} - %msg%n"
  file.name: app.log
  file.path: C:\my_market\src\main\resources\

#for .properties
#server.port=8189
#server.servlet.context-path=/app
